# server properties
server:
  port: 8082

# spring properties
spring:
  application:
    name: PROCESS-PENSION-SERVICE 
    
# Configure Database here
  datasource:
    url: jdbc:h2:mem:process_pension_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      defaultZone:   http://35.89.144.76:8761/eureka/ 

url.app.authservice: http://35.89.218.77:8081
url.app.psdtservice: http://54.185.195.66:8083
url.app.pdbservice:  http://34.212.32.125:8084
      
logging:
  level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       