# server properties
server:
  port: 8082

# spring properties
spring:
  application:
    name: PROCESS-PENSION-SERVICE 
    
# Configure Database here
  datasource:
    url: jdbc:h2:mem:process_pension_db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # add public IP link here
      #defaultZone:   http://35.89.144.76:8761/eureka/
       defaultZone:   http://localhost:8761/eureka/  

url.app.authservice: http://54.212.45.67:8081
url.app.psdtservice: http://18.236.102.73:8083
url.app.pdservice:   http://52.25.1.12:8084
      
logging:
  level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       